apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networkdemo-petclinic

resources:
  - namespace.yaml
  - petclinic-deployment.yaml
  - petclinic-route.yaml
  - petclinic-svc.yaml
  - petclinicdb-secret.yaml
  - network-policy-allow-from-same-namespace.yaml
